# Generated by Django 6.0.1 on 2026-02-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fullName',
            new_name='full_Name',
        ),
    ]
